import { Timestamp } from "firebase/firestore";

export const mockAssessments = [
  {
    id: "assessment-1",
    title: "CMMC Level 1 - Week 4 Quiz",
    description: "Assessment covering Access Control and Identification & Authentication domains",
    type: "quiz",
    cohortId: "cohort-cmmc-1",
    cohortTitle: "CMMC Level 1 Certification - Spring 2026",
    instructorId: "instructor-1",
    status: "published",
    totalQuestions: 20,
    passingScore: 70,
    timeLimit: 45, // minutes
    attempts: 1,
    dueDate: Timestamp.fromDate(new Date(Date.now() + 5 * 24 * 60 * 60 * 1000)),
    createdAt: Timestamp.fromDate(new Date(Date.now() - 10 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.now(),
    submissions: 14,
    averageScore: 82,
    completionRate: 78,
  },
  {
    id: "assessment-2",
    title: "CMMC Level 2 - Midterm Exam",
    description: "Comprehensive midterm covering all domains studied in weeks 1-6",
    type: "exam",
    cohortId: "cohort-cmmc-2",
    cohortTitle: "CMMC Level 2 Advanced Training",
    instructorId: "instructor-1",
    status: "published",
    totalQuestions: 50,
    passingScore: 75,
    timeLimit: 120,
    attempts: 2,
    dueDate: Timestamp.fromDate(new Date(Date.now() + 3 * 24 * 60 * 60 * 1000)),
    createdAt: Timestamp.fromDate(new Date(Date.now() - 15 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.now(),
    submissions: 8,
    averageScore: 76,
    completionRate: 67,
  },
  {
    id: "assessment-3",
    title: "Security Policy Development Assignment",
    description: "Create a comprehensive security policy document for your organization",
    type: "assignment",
    cohortId: "cohort-cmmc-1",
    cohortTitle: "CMMC Level 1 Certification - Spring 2026",
    instructorId: "instructor-1",
    status: "published",
    totalQuestions: 0,
    passingScore: 70,
    timeLimit: null,
    attempts: 1,
    dueDate: Timestamp.fromDate(new Date(Date.now() + 7 * 24 * 60 * 60 * 1000)),
    createdAt: Timestamp.fromDate(new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.now(),
    submissions: 12,
    averageScore: 85,
    completionRate: 67,
  },
  {
    id: "assessment-4",
    title: "CMMC Fundamentals - Final Exam",
    description: "Final comprehensive exam covering all course material",
    type: "exam",
    cohortId: "cohort-cmmc-3",
    cohortTitle: "CMMC Fundamentals - Fast Track",
    instructorId: "instructor-1",
    status: "completed",
    totalQuestions: 40,
    passingScore: 70,
    timeLimit: 90,
    attempts: 1,
    dueDate: Timestamp.fromDate(new Date(Date.now() - 35 * 24 * 60 * 60 * 1000)),
    createdAt: Timestamp.fromDate(new Date(Date.now() - 45 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.fromDate(new Date(Date.now() - 35 * 24 * 60 * 60 * 1000)),
    submissions: 28,
    averageScore: 88,
    completionRate: 100,
  },
  {
    id: "assessment-5",
    title: "Week 2 Knowledge Check",
    description: "Quick knowledge check on System and Communications Protection",
    type: "quiz",
    cohortId: "cohort-cmmc-2",
    cohortTitle: "CMMC Level 2 Advanced Training",
    instructorId: "instructor-1",
    status: "published",
    totalQuestions: 10,
    passingScore: 70,
    timeLimit: 20,
    attempts: 2,
    dueDate: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    createdAt: Timestamp.fromDate(new Date(Date.now() - 8 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.now(),
    submissions: 10,
    averageScore: 79,
    completionRate: 83,
  },
  {
    id: "assessment-6",
    title: "Risk Assessment Framework Project",
    description: "Develop a risk assessment framework for a defense contractor",
    type: "assignment",
    cohortId: "cohort-cmmc-2",
    cohortTitle: "CMMC Level 2 Advanced Training",
    instructorId: "instructor-1",
    status: "draft",
    totalQuestions: 0,
    passingScore: 75,
    timeLimit: null,
    attempts: 1,
    dueDate: Timestamp.fromDate(new Date(Date.now() + 14 * 24 * 60 * 60 * 1000)),
    createdAt: Timestamp.fromDate(new Date(Date.now() - 3 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.now(),
    submissions: 0,
    averageScore: 0,
    completionRate: 0,
  },
  {
    id: "assessment-7",
    title: "Incident Response Planning Exercise",
    description: "Create an incident response plan based on a simulated security breach",
    type: "assignment",
    cohortId: "cohort-cmmc-1",
    cohortTitle: "CMMC Level 1 Certification - Spring 2026",
    instructorId: "instructor-1",
    status: "published",
    totalQuestions: 0,
    passingScore: 70,
    timeLimit: null,
    attempts: 1,
    dueDate: Timestamp.fromDate(new Date(Date.now() + 10 * 24 * 60 * 60 * 1000)),
    createdAt: Timestamp.fromDate(new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.now(),
    submissions: 9,
    averageScore: 81,
    completionRate: 50,
  }
];
