export const mockAuditLogs = [
  {
    id: "log-1",
    timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    userId: "user-admin-001",
    action: "user_created",
    resource: "user",
    resourceId: "user-new-123",
    ipAddress: "192.168.1.100",
    details: {
      email: "newuser@example.com",
      role: "sme",
      createdBy: "admin-001",
    },
  },
  {
    id: "log-2",
    timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    userId: "user-qa-002",
    action: "proof_pack_reviewed",
    resource: "proof_pack",
    resourceId: "pack-aerospace-456",
    ipAddress: "10.0.0.45",
    details: {
      decision: "approved",
      score: 92,
      reviewer: "Sarah Mitchell",
      certifications: ["AS9100", "ISO 9001"],
    },
  },
  {
    id: "log-3",
    timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    userId: "user-admin-001",
    action: "role_assigned",
    resource: "user",
    resourceId: "user-instructor-789",
    ipAddress: "192.168.1.100",
    details: {
      previousRole: "sme",
      newRole: "instructor",
      assignedBy: "admin-001",
      reason: "Promotion to instructor role",
    },
  },
  {
    id: "log-4",
    timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    userId: "user-buyer-003",
    action: "introduction_requested",
    resource: "introduction",
    resourceId: "intro-defense-321",
    ipAddress: "172.16.0.23",
    details: {
      smeId: "sme-defense-101",
      buyerCompany: "Defense Procurement Corp",
      requestType: "urgent",
    },
  },
  {
    id: "log-5",
    timestamp: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    userId: "user-admin-001",
    action: "permission_added",
    resource: "user",
    resourceId: "user-partner-555",
    ipAddress: "192.168.1.100",
    details: {
      permission: "manage_leads",
      grantedBy: "admin-001",
      scope: "organization",
    },
  },
  {
    id: "log-6",
    timestamp: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    userId: "user-sme-004",
    action: "cohort_enrolled",
    resource: "cohort",
    resourceId: "cohort-cmmc-202",
    ipAddress: "203.0.113.42",
    details: {
      cohortTitle: "CMMC Level 2 Advanced Training",
      enrollmentDate: new Date().toISOString(),
      paymentStatus: "completed",
    },
  },
  {
    id: "log-7",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    userId: "user-admin-001",
    action: "user_suspended",
    resource: "user",
    resourceId: "user-violation-666",
    ipAddress: "192.168.1.100",
    details: {
      reason: "Terms of Service violation",
      suspendedBy: "admin-001",
      duration: "30 days",
      appealable: true,
    },
  },
  {
    id: "log-8",
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    userId: "user-instructor-005",
    action: "assessment_published",
    resource: "assessment",
    resourceId: "assessment-quiz-789",
    ipAddress: "198.51.100.15",
    details: {
      assessmentTitle: "CMMC Level 1 - Week 4 Quiz",
      cohortId: "cohort-cmmc-1",
      dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    },
  },
  {
    id: "log-9",
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    userId: "user-admin-002",
    action: "payment_dispute",
    resource: "revenue",
    resourceId: "payment-dispute-101",
    ipAddress: "192.168.1.101",
    details: {
      amount: 4500,
      currency: "USD",
      disputeReason: "Service not delivered",
      status: "under_review",
    },
  },
  {
    id: "log-10",
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    userId: "user-partner-006",
    action: "lead_created",
    resource: "lead",
    resourceId: "lead-aerospace-888",
    ipAddress: "10.0.1.50",
    details: {
      leadSource: "website_form",
      company: "Aerospace Solutions Inc",
      value: 25000,
      assignedTo: "sales-rep-003",
    },
  },
  {
    id: "log-11",
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    userId: "user-admin-001",
    action: "permission_removed",
    resource: "user",
    resourceId: "user-contractor-777",
    ipAddress: "192.168.1.100",
    details: {
      permission: "access_financials",
      removedBy: "admin-001",
      reason: "Contract ended",
    },
  },
  {
    id: "log-12",
    timestamp: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    userId: "user-sme-007",
    action: "proof_pack_submitted",
    resource: "proof_pack",
    resourceId: "pack-medical-999",
    ipAddress: "172.16.5.88",
    details: {
      title: "ISO 13485 Medical Device QMS",
      documentCount: 17,
      certifications: ["ISO 13485", "FDA 21 CFR Part 820"],
      submittedFor: "qa_review",
    },
  },
  {
    id: "log-13",
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    userId: "user-buyer-008",
    action: "content_downloaded",
    resource: "content",
    resourceId: "content-whitepaper-555",
    ipAddress: "203.0.113.99",
    details: {
      contentType: "whitepaper",
      title: "CMMC Compliance Guide 2026",
      fileSize: "2.4 MB",
    },
  },
  {
    id: "log-14",
    timestamp: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
    userId: "user-admin-003",
    action: "revenue_dispute",
    resource: "revenue",
    resourceId: "revenue-dispute-202",
    ipAddress: "192.168.1.102",
    details: {
      amount: 6500,
      currency: "USD",
      disputeType: "commission_calculation",
      parties: ["partner-001", "admin-003"],
    },
  },
  {
    id: "log-15",
    timestamp: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    userId: "user-instructor-009",
    action: "cohort_created",
    resource: "cohort",
    resourceId: "cohort-summer-303",
    ipAddress: "198.51.100.77",
    details: {
      title: "CMMC Level 2 - Summer Intensive",
      duration: "12 weeks",
      maxParticipants: 20,
      price: 6500,
    },
  },
  {
    id: "log-16",
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    userId: "user-qa-010",
    action: "review_completed",
    resource: "qa_review",
    resourceId: "review-nadcap-444",
    ipAddress: "10.0.0.88",
    details: {
      smeCompany: "Titanium Heat Treating Specialists",
      reviewType: "spot_audit",
      score: 72,
      findings: 3,
      decision: "conditional_approval",
    },
  },
  {
    id: "log-17",
    timestamp: new Date(Date.now() - 15 * 60 * 60 * 1000).toISOString(),
    userId: "user-admin-001",
    action: "user_deleted",
    resource: "user",
    resourceId: "user-inactive-111",
    ipAddress: "192.168.1.100",
    details: {
      reason: "Account closure requested by user",
      deletedBy: "admin-001",
      dataRetention: "90 days",
      gdprCompliant: true,
    },
  },
  {
    id: "log-18",
    timestamp: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    userId: "user-partner-011",
    action: "event_registered",
    resource: "event",
    resourceId: "event-webinar-666",
    ipAddress: "172.16.8.45",
    details: {
      eventTitle: "CMMC 2.0 Updates Webinar",
      eventDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
      registrationType: "paid",
    },
  },
  {
    id: "log-19",
    timestamp: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    userId: "user-sme-012",
    action: "profile_updated",
    resource: "user",
    resourceId: "user-sme-012",
    ipAddress: "203.0.113.150",
    details: {
      fieldsUpdated: ["certifications", "expertise", "hourlyRate"],
      previousCertifications: ["ISO 9001"],
      newCertifications: ["ISO 9001", "AS9100"],
    },
  },
  {
    id: "log-20",
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    userId: "user-buyer-013",
    action: "introduction_accepted",
    resource: "introduction",
    resourceId: "intro-manufacturing-777",
    ipAddress: "198.51.100.200",
    details: {
      smeId: "sme-manufacturing-606",
      acceptedBy: "buyer-013",
      nextSteps: "Schedule initial consultation",
    },
  },
];
