import { Timestamp } from "firebase/firestore";

export const mockSMEProfiles = [
  {
    id: "sme-1",
    companyName: "Advanced Composites Inc",
    contactName: "Dr. Sarah Chen",
    email: "sarah.chen@advancedcomposites.com",
    phone: "+1-555-0101",
    industry: "Aerospace Manufacturing",
    specialization: "Carbon Fiber Composites",
    certifications: ["AS9100", "NADCAP", "ISO 9001"],
    yearsInBusiness: 15,
    employeeCount: 45,
    annualRevenue: 8500000,
    location: "Seattle, WA",
    serviceOfferings: [
      "Custom composite design",
      "Prototype development",
      "Production manufacturing",
      "Quality testing"
    ],
    pastClients: ["Boeing", "SpaceX", "Lockheed Martin"],
    rating: 4.8,
    reviewCount: 24,
    responseTime: "< 2 hours",
    completionRate: 98,
    verified: true,
    proofPacksCount: 3,
    introductionsCount: 12,
    createdAt: Timestamp.fromDate(new Date(Date.now() - 180 * 24 * 60 * 60 * 1000)),
  },
  {
    id: "sme-2",
    companyName: "Precision Machining Solutions",
    contactName: "Michael Torres",
    email: "m.torres@precisionmachining.com",
    phone: "+1-555-0102",
    industry: "Defense Manufacturing",
    specialization: "CNC Machining & Precision Parts",
    certifications: ["ITAR", "AS9100", "ISO 9001"],
    yearsInBusiness: 22,
    employeeCount: 78,
    annualRevenue: 12000000,
    location: "Phoenix, AZ",
    serviceOfferings: [
      "5-axis CNC machining",
      "Precision grinding",
      "Assembly services",
      "Reverse engineering"
    ],
    pastClients: ["Raytheon", "Northrop Grumman", "General Dynamics"],
    rating: 4.9,
    reviewCount: 31,
    responseTime: "< 1 hour",
    completionRate: 99,
    verified: true,
    proofPacksCount: 5,
    introductionsCount: 18,
    createdAt: Timestamp.fromDate(new Date(Date.now() - 240 * 24 * 60 * 60 * 1000)),
  },
  {
    id: "sme-3",
    companyName: "Quantum Electronics Corp",
    contactName: "Dr. Emily Rodriguez",
    email: "e.rodriguez@quantumelectronics.com",
    phone: "+1-555-0103",
    industry: "Electronics & Avionics",
    specialization: "Embedded Systems & Avionics",
    certifications: ["AS9100", "DO-178C", "ISO 27001"],
    yearsInBusiness: 12,
    employeeCount: 32,
    annualRevenue: 6200000,
    location: "Austin, TX",
    serviceOfferings: [
      "Avionics design",
      "Embedded software",
      "Hardware integration",
      "Testing & certification"
    ],
    pastClients: ["Gulfstream", "Textron Aviation", "Bell Helicopter"],
    rating: 4.7,
    reviewCount: 19,
    responseTime: "< 3 hours",
    completionRate: 96,
    verified: true,
    proofPacksCount: 2,
    introductionsCount: 8,
    createdAt: Timestamp.fromDate(new Date(Date.now() - 150 * 24 * 60 * 60 * 1000)),
  },
  {
    id: "sme-4",
    companyName: "TitanForge Materials",
    contactName: "James Patterson",
    email: "j.patterson@titanforge.com",
    phone: "+1-555-0104",
    industry: "Materials Science",
    specialization: "Titanium Alloys & Heat Treatment",
    certifications: ["NADCAP", "AS9100", "ISO 9001"],
    yearsInBusiness: 18,
    employeeCount: 56,
    annualRevenue: 9800000,
    location: "Denver, CO",
    serviceOfferings: [
      "Titanium forging",
      "Heat treatment",
      "Material testing",
      "Metallurgical consulting"
    ],
    pastClients: ["Pratt & Whitney", "GE Aviation", "Rolls-Royce"],
    rating: 4.9,
    reviewCount: 28,
    responseTime: "< 2 hours",
    completionRate: 97,
    verified: true,
    proofPacksCount: 4,
    introductionsCount: 15,
    createdAt: Timestamp.fromDate(new Date(Date.now() - 200 * 24 * 60 * 60 * 1000)),
  },
  {
    id: "sme-5",
    companyName: "AeroTest Labs",
    contactName: "Dr. Lisa Wang",
    email: "l.wang@aerotestlabs.com",
    phone: "+1-555-0105",
    industry: "Testing & Certification",
    specialization: "Non-Destructive Testing",
    certifications: ["NADCAP", "ISO 17025", "AS9100"],
    yearsInBusiness: 10,
    employeeCount: 28,
    annualRevenue: 4500000,
    location: "San Diego, CA",
    serviceOfferings: [
      "X-ray inspection",
      "Ultrasonic testing",
      "Eddy current testing",
      "Certification support"
    ],
    pastClients: ["Boeing", "Airbus", "Spirit AeroSystems"],
    rating: 4.8,
    reviewCount: 22,
    responseTime: "< 4 hours",
    completionRate: 95,
    verified: true,
    proofPacksCount: 2,
    introductionsCount: 10,
    createdAt: Timestamp.fromDate(new Date(Date.now() - 120 * 24 * 60 * 60 * 1000)),
  },
];

export const mockBuyerIntroductions = [
  {
    id: "intro-buyer-1",
    buyerId: "current-buyer-id",
    buyerCompany: "Lockheed Martin",
    smeId: "sme-1",
    smeCompany: "Advanced Composites Inc",
    partnerId: "partner-1",
    partnerName: "Strategic Defense Partners",
    status: "accepted",
    stage: "meeting_scheduled",
    estimatedValue: 750000,
    projectDescription: "Carbon fiber wing components for F-35 program",
    meetingDate: Timestamp.fromDate(new Date(Date.now() + 7 * 24 * 60 * 60 * 1000)),
    requestedAt: Timestamp.fromDate(new Date(Date.now() - 14 * 24 * 60 * 60 * 1000)),
    respondedAt: Timestamp.fromDate(new Date(Date.now() - 10 * 24 * 60 * 60 * 1000)),
    notes: "Initial meeting scheduled to discuss technical requirements and timeline",
    priority: "high",
  },
  {
    id: "intro-buyer-2",
    buyerId: "current-buyer-id",
    buyerCompany: "Lockheed Martin",
    smeId: "sme-2",
    smeCompany: "Precision Machining Solutions",
    partnerId: "partner-2",
    partnerName: "Aerospace Alliance Group",
    status: "accepted",
    stage: "proposal_submitted",
    estimatedValue: 1200000,
    projectDescription: "Precision machined components for missile guidance systems",
    meetingDate: Timestamp.fromDate(new Date(Date.now() - 21 * 24 * 60 * 60 * 1000)),
    requestedAt: Timestamp.fromDate(new Date(Date.now() - 35 * 24 * 60 * 60 * 1000)),
    respondedAt: Timestamp.fromDate(new Date(Date.now() - 30 * 24 * 60 * 60 * 1000)),
    notes: "Proposal received, under technical review by engineering team",
    priority: "high",
  },
  {
    id: "intro-buyer-3",
    buyerId: "current-buyer-id",
    buyerCompany: "Lockheed Martin",
    smeId: "sme-3",
    smeCompany: "Quantum Electronics Corp",
    partnerId: "partner-1",
    partnerName: "Strategic Defense Partners",
    status: "pending",
    stage: "introduction_sent",
    estimatedValue: 450000,
    projectDescription: "Avionics upgrade for C-130 fleet",
    requestedAt: Timestamp.fromDate(new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)),
    notes: "Awaiting SME response",
    priority: "medium",
  },
  {
    id: "intro-buyer-4",
    buyerId: "current-buyer-id",
    buyerCompany: "Lockheed Martin",
    smeId: "sme-4",
    smeCompany: "TitanForge Materials",
    partnerId: "partner-3",
    partnerName: "Defense Innovation Network",
    status: "accepted",
    stage: "closed_won",
    estimatedValue: 980000,
    projectDescription: "Titanium landing gear components",
    meetingDate: Timestamp.fromDate(new Date(Date.now() - 60 * 24 * 60 * 60 * 1000)),
    requestedAt: Timestamp.fromDate(new Date(Date.now() - 90 * 24 * 60 * 60 * 1000)),
    respondedAt: Timestamp.fromDate(new Date(Date.now() - 85 * 24 * 60 * 60 * 1000)),
    contractSignedAt: Timestamp.fromDate(new Date(Date.now() - 30 * 24 * 60 * 60 * 1000)),
    notes: "Contract signed, production starting Q2",
    priority: "high",
  },
  {
    id: "intro-buyer-5",
    buyerId: "current-buyer-id",
    buyerCompany: "Lockheed Martin",
    smeId: "sme-5",
    smeCompany: "AeroTest Labs",
    partnerId: "partner-2",
    partnerName: "Aerospace Alliance Group",
    status: "declined",
    stage: "introduction_sent",
    estimatedValue: 180000,
    projectDescription: "NDT services for airframe inspection",
    requestedAt: Timestamp.fromDate(new Date(Date.now() - 45 * 24 * 60 * 60 * 1000)),
    respondedAt: Timestamp.fromDate(new Date(Date.now() - 40 * 24 * 60 * 60 * 1000)),
    notes: "SME declined due to capacity constraints",
    priority: "low",
  },
];

export const mockSavedSMEs = [
  {
    id: "saved-1",
    buyerId: "current-buyer-id",
    smeId: "sme-1",
    smeCompany: "Advanced Composites Inc",
    savedAt: Timestamp.fromDate(new Date(Date.now() - 30 * 24 * 60 * 60 * 1000)),
    notes: "Excellent composite capabilities, consider for future wing projects",
    tags: ["composites", "aerospace", "high-priority"],
    folder: "Preferred Vendors",
  },
  {
    id: "saved-2",
    buyerId: "current-buyer-id",
    smeId: "sme-2",
    smeCompany: "Precision Machining Solutions",
    savedAt: Timestamp.fromDate(new Date(Date.now() - 45 * 24 * 60 * 60 * 1000)),
    notes: "Top-tier machining quality, ITAR compliant",
    tags: ["machining", "defense", "itar"],
    folder: "Preferred Vendors",
  },
  {
    id: "saved-3",
    buyerId: "current-buyer-id",
    smeId: "sme-4",
    smeCompany: "TitanForge Materials",
    savedAt: Timestamp.fromDate(new Date(Date.now() - 60 * 24 * 60 * 60 * 1000)),
    notes: "Reliable titanium supplier, good lead times",
    tags: ["materials", "titanium", "reliable"],
    folder: "Materials Suppliers",
  },
  {
    id: "saved-4",
    buyerId: "current-buyer-id",
    smeId: "sme-3",
    smeCompany: "Quantum Electronics Corp",
    savedAt: Timestamp.fromDate(new Date(Date.now() - 20 * 24 * 60 * 60 * 1000)),
    notes: "Innovative avionics solutions, watch for future opportunities",
    tags: ["electronics", "avionics", "innovation"],
    folder: "Electronics",
  },
];

export const mockSharedProofPacks = [
  {
    id: "pack-1",
    title: "Advanced Composites Portfolio",
    smeId: "sme-1",
    smeCompany: "Advanced Composites Inc",
    sharedBy: "partner-1",
    sharedByName: "Strategic Defense Partners",
    sharedAt: Timestamp.fromDate(new Date(Date.now() - 15 * 24 * 60 * 60 * 1000)),
    description: "Comprehensive portfolio of composite manufacturing capabilities",
    documents: [
      {
        id: "doc-1",
        name: "AS9100 Certificate",
        type: "certification",
        url: "/documents/as9100-cert.pdf",
        uploadedAt: Timestamp.fromDate(new Date(Date.now() - 90 * 24 * 60 * 60 * 1000)),
      },
      {
        id: "doc-2",
        name: "F-35 Wing Component Case Study",
        type: "case_study",
        url: "/documents/f35-case-study.pdf",
        uploadedAt: Timestamp.fromDate(new Date(Date.now() - 60 * 24 * 60 * 60 * 1000)),
      },
      {
        id: "doc-3",
        name: "Composite Testing Results",
        type: "technical",
        url: "/documents/composite-testing.pdf",
        uploadedAt: Timestamp.fromDate(new Date(Date.now() - 45 * 24 * 60 * 60 * 1000)),
      },
    ],
    tags: ["composites", "aerospace", "certified"],
    viewCount: 8,
    downloadCount: 3,
  },
  {
    id: "pack-2",
    title: "Precision Machining Capabilities",
    smeId: "sme-2",
    smeCompany: "Precision Machining Solutions",
    sharedBy: "partner-2",
    sharedByName: "Aerospace Alliance Group",
    sharedAt: Timestamp.fromDate(new Date(Date.now() - 25 * 24 * 60 * 60 * 1000)),
    description: "5-axis CNC machining and precision parts manufacturing",
    documents: [
      {
        id: "doc-4",
        name: "ITAR Certification",
        type: "certification",
        url: "/documents/itar-cert.pdf",
        uploadedAt: Timestamp.fromDate(new Date(Date.now() - 120 * 24 * 60 * 60 * 1000)),
      },
      {
        id: "doc-5",
        name: "Missile Component Case Study",
        type: "case_study",
        url: "/documents/missile-case-study.pdf",
        uploadedAt: Timestamp.fromDate(new Date(Date.now() - 75 * 24 * 60 * 60 * 1000)),
      },
      {
        id: "doc-6",
        name: "Quality Inspection Report",
        type: "technical",
        url: "/documents/quality-report.pdf",
        uploadedAt: Timestamp.fromDate(new Date(Date.now() - 50 * 24 * 60 * 60 * 1000)),
      },
    ],
    tags: ["machining", "defense", "itar"],
    viewCount: 12,
    downloadCount: 5,
  },
  {
    id: "pack-3",
    title: "Titanium Manufacturing Excellence",
    smeId: "sme-4",
    smeCompany: "TitanForge Materials",
    sharedBy: "partner-3",
    sharedByName: "Defense Innovation Network",
    sharedAt: Timestamp.fromDate(new Date(Date.now() - 40 * 24 * 60 * 60 * 1000)),
    description: "Titanium forging and heat treatment capabilities",
    documents: [
      {
        id: "doc-7",
        name: "NADCAP Certification",
        type: "certification",
        url: "/documents/nadcap-cert.pdf",
        uploadedAt: Timestamp.fromDate(new Date(Date.now() - 100 * 24 * 60 * 60 * 1000)),
      },
      {
        id: "doc-8",
        name: "Landing Gear Project",
        type: "case_study",
        url: "/documents/landing-gear.pdf",
        uploadedAt: Timestamp.fromDate(new Date(Date.now() - 70 * 24 * 60 * 60 * 1000)),
      },
    ],
    tags: ["titanium", "materials", "certified"],
    viewCount: 6,
    downloadCount: 2,
  },
];

export const mockBuyerDashboardStats = {
  activeIntroductions: 3,
  pendingResponses: 1,
  scheduledMeetings: 1,
  closedDeals: 1,
  totalSpend: 2930000,
  savedSMEs: 4,
  sharedProofPacks: 3,
  recentActivity: [
    {
      id: "activity-1",
      type: "introduction_accepted",
      message: "Advanced Composites Inc accepted your introduction request",
      timestamp: Timestamp.fromDate(new Date(Date.now() - 10 * 24 * 60 * 60 * 1000)),
      smeCompany: "Advanced Composites Inc",
    },
    {
      id: "activity-2",
      type: "meeting_scheduled",
      message: "Meeting scheduled with Advanced Composites Inc",
      timestamp: Timestamp.fromDate(new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)),
      smeCompany: "Advanced Composites Inc",
    },
    {
      id: "activity-3",
      type: "proposal_received",
      message: "Proposal received from Precision Machining Solutions",
      timestamp: Timestamp.fromDate(new Date(Date.now() - 14 * 24 * 60 * 60 * 1000)),
      smeCompany: "Precision Machining Solutions",
    },
    {
      id: "activity-4",
      type: "proof_pack_shared",
      message: "Strategic Defense Partners shared a proof pack",
      timestamp: Timestamp.fromDate(new Date(Date.now() - 15 * 24 * 60 * 60 * 1000)),
      partnerName: "Strategic Defense Partners",
    },
    {
      id: "activity-5",
      type: "contract_signed",
      message: "Contract signed with TitanForge Materials",
      timestamp: Timestamp.fromDate(new Date(Date.now() - 30 * 24 * 60 * 60 * 1000)),
      smeCompany: "TitanForge Materials",
    },
  ],
};
