import { 
  CrawledPage, 
  CrawlProgress, 
  MigrationReport, 
  ImageAsset, 
  VideoAsset, 
  DocumentAsset,
  SiteStructure,
  NavigationItem,
} from '../types/content-migration';

export const mockCrawlProgress: CrawlProgress = {
  totalPagesDiscovered: 47,
  pagesCrawled: 47,
  pagesRemaining: 0,
  imagesFound: 156,
  imagesDownloaded: 142,
  videosFound: 8,
  documentsFound: 12,
  documentsDownloaded: 12,
  errors: [
    {
      url: 'https://www.kdm-assoc.com/old-page',
      errorType: '404',
      message: 'Page not found',
      timestamp: '2026-01-18T15:30:00Z',
    },
    {
      url: 'https://www.kdm-assoc.com/images/legacy-banner.jpg',
      errorType: 'network',
      message: 'Failed to download image: timeout',
      timestamp: '2026-01-18T15:45:00Z',
    },
  ],
  startedAt: '2026-01-18T15:00:00Z',
  lastUpdatedAt: '2026-01-18T16:30:00Z',
  status: 'completed',
};

export const mockSiteStructure: SiteStructure = {
  primaryNavigation: [
    {
      label: 'Home',
      url: '/',
      children: [],
      order: 0,
    },
    {
      label: 'About',
      url: '/about',
      children: [
        { label: 'Our Story', url: '/about/story', children: [], order: 0 },
        { label: 'Our Team', url: '/about/team', children: [], order: 1 },
        { label: 'Careers', url: '/about/careers', children: [], order: 2 },
      ],
      order: 1,
    },
    {
      label: 'Services',
      url: '/services',
      children: [
        { label: 'ISO Certification', url: '/services/iso-certification', children: [], order: 0 },
        { label: 'CMMC Compliance', url: '/services/cmmc-compliance', children: [], order: 1 },
        { label: 'Lean Manufacturing', url: '/services/lean-manufacturing', children: [], order: 2 },
        { label: 'Quality Systems', url: '/services/quality-systems', children: [], order: 3 },
        { label: 'Training', url: '/services/training', children: [], order: 4 },
      ],
      order: 2,
    },
    {
      label: 'Industries',
      url: '/industries',
      children: [
        { label: 'Aerospace', url: '/industries/aerospace', children: [], order: 0 },
        { label: 'Defense', url: '/industries/defense', children: [], order: 1 },
        { label: 'Manufacturing', url: '/industries/manufacturing', children: [], order: 2 },
      ],
      order: 3,
    },
    {
      label: 'Resources',
      url: '/resources',
      children: [
        { label: 'Blog', url: '/blog', children: [], order: 0 },
        { label: 'Case Studies', url: '/case-studies', children: [], order: 1 },
        { label: 'Whitepapers', url: '/resources/whitepapers', children: [], order: 2 },
        { label: 'Webinars', url: '/resources/webinars', children: [], order: 3 },
      ],
      order: 4,
    },
    {
      label: 'Contact',
      url: '/contact',
      children: [],
      order: 5,
    },
  ],
  secondaryNavigation: [
    { label: 'Client Portal', url: '/portal', children: [], order: 0 },
    { label: 'Partner Login', url: '/partner-login', children: [], order: 1 },
  ],
  footerNavigation: [
    { label: 'Privacy Policy', url: '/privacy', children: [], order: 0 },
    { label: 'Terms of Service', url: '/terms', children: [], order: 1 },
    { label: 'Sitemap', url: '/sitemap', children: [], order: 2 },
  ],
  sitemapUrls: [
    'https://www.kdm-assoc.com/',
    'https://www.kdm-assoc.com/about',
    'https://www.kdm-assoc.com/about/team',
    'https://www.kdm-assoc.com/services',
    'https://www.kdm-assoc.com/services/iso-certification',
    'https://www.kdm-assoc.com/services/cmmc-compliance',
    'https://www.kdm-assoc.com/contact',
  ],
};

export const mockCrawledPages: CrawledPage[] = [
  {
    url: 'https://www.kdm-assoc.com/',
    slug: 'home',
    title: 'KDM Associates - Quality Management & Compliance Solutions',
    pageType: 'home',
    publishedDate: null,
    lastModified: '2026-01-15T10:00:00Z',
    metadata: {
      url: 'https://www.kdm-assoc.com/',
      slug: 'home',
      title: 'KDM Associates - Quality Management & Compliance Solutions',
      metaDescription: 'KDM Associates provides expert quality management, ISO certification, and CMMC compliance solutions for aerospace and defense manufacturers.',
      metaKeywords: ['quality management', 'ISO certification', 'CMMC compliance', 'aerospace', 'defense'],
      ogTitle: 'KDM Associates - Quality Management & Compliance Solutions',
      ogDescription: 'Expert quality management and compliance solutions for manufacturers.',
      ogImage: 'https://www.kdm-assoc.com/images/og-home.jpg',
      canonicalUrl: 'https://www.kdm-assoc.com/',
      lastModified: '2026-01-15T10:00:00Z',
      breadcrumb: ['Home'],
    },
    content: {
      hero: {
        heading: 'Quality Management Excellence',
        subheading: 'Helping manufacturers achieve certification and compliance with confidence',
        image: '/images/hero-home.jpg',
        cta: {
          text: 'Get Started',
          link: '/contact',
        },
      },
      sections: [
        {
          type: 'text',
          heading: 'Why Choose KDM Associates?',
          content: 'With over 25 years of experience in quality management and compliance, KDM Associates has helped hundreds of manufacturers achieve their certification goals.',
          images: [],
          videos: [],
          order: 0,
        },
        {
          type: 'image-text',
          heading: 'Our Services',
          content: 'From ISO 9001 to CMMC Level 2, we provide comprehensive certification and compliance services tailored to your industry.',
          images: ['/images/services-overview.jpg'],
          videos: [],
          order: 1,
        },
        {
          type: 'testimonial',
          heading: 'What Our Clients Say',
          content: '"KDM Associates helped us achieve AS9100 certification in record time. Their expertise and guidance were invaluable." - John Smith, CEO, Precision Manufacturing Inc.',
          images: [],
          videos: [],
          order: 2,
        },
      ],
    },
    seo: {
      keywords: ['quality management', 'ISO certification', 'CMMC compliance'],
      ogImage: 'https://www.kdm-assoc.com/images/og-home.jpg',
      structuredData: {
        '@context': 'https://schema.org',
        '@type': 'Organization',
        name: 'KDM Associates',
        url: 'https://www.kdm-assoc.com',
      },
    },
    navigation: {
      breadcrumb: ['Home'],
      relatedPages: ['/about', '/services', '/contact'],
    },
    media: {
      images: [],
      videos: [],
      documents: [],
    },
    forms: [
      {
        id: 'form-contact-home',
        purpose: 'contact',
        action: '/api/contact',
        method: 'POST',
        fields: [
          { name: 'name', type: 'text', label: 'Name', placeholder: 'Your name', required: true },
          { name: 'email', type: 'email', label: 'Email', placeholder: 'your@email.com', required: true },
          { name: 'message', type: 'textarea', label: 'Message', placeholder: 'How can we help?', required: true },
        ],
        submitButtonText: 'Send Message',
        parentPageUrl: 'https://www.kdm-assoc.com/',
      },
    ],
    wordCount: 850,
    httpStatus: 200,
    crawledAt: '2026-01-18T15:05:00Z',
  },
  {
    url: 'https://www.kdm-assoc.com/about',
    slug: 'about',
    title: 'About KDM Associates - Our Story & Mission',
    pageType: 'about',
    publishedDate: null,
    lastModified: '2025-12-01T10:00:00Z',
    metadata: {
      url: 'https://www.kdm-assoc.com/about',
      slug: 'about',
      title: 'About KDM Associates - Our Story & Mission',
      metaDescription: 'Learn about KDM Associates, our mission, values, and 25+ years of experience helping manufacturers achieve quality excellence.',
      metaKeywords: ['about KDM', 'quality consulting', 'company history'],
      ogTitle: 'About KDM Associates',
      ogDescription: 'Our story and mission in quality management.',
      ogImage: 'https://www.kdm-assoc.com/images/og-about.jpg',
      canonicalUrl: 'https://www.kdm-assoc.com/about',
      lastModified: '2025-12-01T10:00:00Z',
      breadcrumb: ['Home', 'About'],
    },
    content: {
      hero: {
        heading: 'About KDM Associates',
        subheading: '25+ years of quality management excellence',
        image: '/images/hero-about.jpg',
      },
      sections: [
        {
          type: 'text',
          heading: 'Our Story',
          content: 'Founded in 1998, KDM Associates began with a simple mission: to help manufacturers achieve quality excellence. Today, we serve clients across aerospace, defense, and manufacturing industries.',
          images: [],
          videos: [],
          order: 0,
        },
        {
          type: 'image-text',
          heading: 'Our Mission',
          content: 'We are committed to providing expert guidance and practical solutions that help our clients achieve and maintain the highest standards of quality and compliance.',
          images: ['/images/mission.jpg'],
          videos: [],
          order: 1,
        },
      ],
    },
    seo: {
      keywords: ['about KDM', 'quality consulting'],
      ogImage: 'https://www.kdm-assoc.com/images/og-about.jpg',
      structuredData: null,
    },
    navigation: {
      breadcrumb: ['Home', 'About'],
      relatedPages: ['/about/team', '/about/careers'],
    },
    media: {
      images: [],
      videos: [],
      documents: [],
    },
    forms: [],
    wordCount: 620,
    httpStatus: 200,
    crawledAt: '2026-01-18T15:10:00Z',
  },
  {
    url: 'https://www.kdm-assoc.com/services/iso-certification',
    slug: 'services-iso-certification',
    title: 'ISO Certification Services - ISO 9001, AS9100, ISO 13485',
    pageType: 'services',
    publishedDate: null,
    lastModified: '2026-01-10T10:00:00Z',
    metadata: {
      url: 'https://www.kdm-assoc.com/services/iso-certification',
      slug: 'services-iso-certification',
      title: 'ISO Certification Services - ISO 9001, AS9100, ISO 13485',
      metaDescription: 'Expert ISO certification consulting for ISO 9001, AS9100, ISO 13485, and more. Get certified faster with KDM Associates.',
      metaKeywords: ['ISO 9001', 'AS9100', 'ISO 13485', 'certification', 'consulting'],
      ogTitle: 'ISO Certification Services',
      ogDescription: 'Get ISO certified with expert guidance.',
      ogImage: 'https://www.kdm-assoc.com/images/og-iso.jpg',
      canonicalUrl: 'https://www.kdm-assoc.com/services/iso-certification',
      lastModified: '2026-01-10T10:00:00Z',
      breadcrumb: ['Home', 'Services', 'ISO Certification'],
    },
    content: {
      hero: {
        heading: 'ISO Certification Services',
        subheading: 'Expert guidance for ISO 9001, AS9100, ISO 13485, and more',
        image: '/images/hero-iso.jpg',
        cta: {
          text: 'Request a Quote',
          link: '/contact?service=iso',
        },
      },
      sections: [
        {
          type: 'text',
          heading: 'Our ISO Certification Expertise',
          content: 'We provide comprehensive ISO certification consulting services, from gap analysis to successful certification audit. Our proven methodology ensures a smooth certification journey.',
          images: [],
          videos: [],
          order: 0,
        },
        {
          type: 'list',
          heading: 'Standards We Support',
          content: 'ISO 9001:2015 Quality Management Systems, AS9100D Aerospace Quality, ISO 13485 Medical Devices, ISO 14001 Environmental Management, ISO 45001 Occupational Health & Safety',
          images: [],
          videos: [],
          order: 1,
        },
        {
          type: 'video',
          heading: 'ISO Certification Process Overview',
          content: 'Watch our video to learn about the ISO certification process and how we can help.',
          images: [],
          videos: ['https://www.youtube.com/watch?v=abc123'],
          order: 2,
        },
      ],
    },
    seo: {
      keywords: ['ISO 9001', 'AS9100', 'ISO certification'],
      ogImage: 'https://www.kdm-assoc.com/images/og-iso.jpg',
      structuredData: null,
    },
    navigation: {
      breadcrumb: ['Home', 'Services', 'ISO Certification'],
      relatedPages: ['/services/cmmc-compliance', '/services/quality-systems'],
    },
    media: {
      images: [],
      videos: [],
      documents: [],
    },
    forms: [],
    wordCount: 1250,
    httpStatus: 200,
    crawledAt: '2026-01-18T15:15:00Z',
  },
  {
    url: 'https://www.kdm-assoc.com/contact',
    slug: 'contact',
    title: 'Contact KDM Associates - Get in Touch',
    pageType: 'contact',
    publishedDate: null,
    lastModified: '2025-11-15T10:00:00Z',
    metadata: {
      url: 'https://www.kdm-assoc.com/contact',
      slug: 'contact',
      title: 'Contact KDM Associates - Get in Touch',
      metaDescription: 'Contact KDM Associates for quality management consulting, ISO certification, and CMMC compliance services. Get a free consultation today.',
      metaKeywords: ['contact', 'consultation', 'quote'],
      ogTitle: 'Contact KDM Associates',
      ogDescription: 'Get in touch with our team.',
      ogImage: null,
      canonicalUrl: 'https://www.kdm-assoc.com/contact',
      lastModified: '2025-11-15T10:00:00Z',
      breadcrumb: ['Home', 'Contact'],
    },
    content: {
      hero: {
        heading: 'Contact Us',
        subheading: 'We\'re here to help with your quality and compliance needs',
        image: null,
      },
      sections: [
        {
          type: 'form',
          heading: 'Send Us a Message',
          content: 'Fill out the form below and we\'ll get back to you within 24 hours.',
          images: [],
          videos: [],
          order: 0,
        },
        {
          type: 'text',
          heading: 'Contact Information',
          content: 'Phone: (555) 123-4567\nEmail: info@kdm-assoc.com\nAddress: 123 Quality Lane, Suite 100, Atlanta, GA 30301',
          images: [],
          videos: [],
          order: 1,
        },
      ],
    },
    seo: {
      keywords: ['contact', 'consultation'],
      ogImage: null,
      structuredData: null,
    },
    navigation: {
      breadcrumb: ['Home', 'Contact'],
      relatedPages: [],
    },
    media: {
      images: [],
      videos: [],
      documents: [],
    },
    forms: [
      {
        id: 'form-contact-main',
        purpose: 'contact',
        action: '/api/contact',
        method: 'POST',
        fields: [
          { name: 'firstName', type: 'text', label: 'First Name', placeholder: null, required: true },
          { name: 'lastName', type: 'text', label: 'Last Name', placeholder: null, required: true },
          { name: 'email', type: 'email', label: 'Email', placeholder: null, required: true },
          { name: 'phone', type: 'tel', label: 'Phone', placeholder: null, required: false },
          { name: 'company', type: 'text', label: 'Company', placeholder: null, required: false },
          { name: 'service', type: 'select', label: 'Service Interest', placeholder: null, required: true, options: ['ISO Certification', 'CMMC Compliance', 'Lean Manufacturing', 'Training', 'Other'] },
          { name: 'message', type: 'textarea', label: 'Message', placeholder: null, required: true },
        ],
        submitButtonText: 'Submit Request',
        parentPageUrl: 'https://www.kdm-assoc.com/contact',
      },
    ],
    wordCount: 320,
    httpStatus: 200,
    crawledAt: '2026-01-18T15:20:00Z',
  },
];

export const mockImages: ImageAsset[] = [
  {
    id: 'img-001',
    sourceUrl: 'https://www.kdm-assoc.com/images/hero-home.jpg',
    localPath: '/kdm-content-migration/media/images/heroes/hero-home.jpg',
    alt: 'Quality management professionals collaborating',
    title: 'KDM Associates Team',
    width: 1920,
    height: 1080,
    format: 'jpg',
    context: 'hero',
    caption: null,
    parentPageUrl: 'https://www.kdm-assoc.com/',
    fileSize: 245000,
    downloaded: true,
  },
  {
    id: 'img-002',
    sourceUrl: 'https://www.kdm-assoc.com/images/logo.svg',
    localPath: '/kdm-content-migration/media/images/logos/logo.svg',
    alt: 'KDM Associates Logo',
    title: 'KDM Associates',
    width: 200,
    height: 60,
    format: 'svg',
    context: 'logo',
    caption: null,
    parentPageUrl: 'https://www.kdm-assoc.com/',
    fileSize: 5200,
    downloaded: true,
  },
  {
    id: 'img-003',
    sourceUrl: 'https://www.kdm-assoc.com/images/team/john-doe.jpg',
    localPath: '/kdm-content-migration/media/images/team/john-doe.jpg',
    alt: 'John Doe, CEO',
    title: 'John Doe',
    width: 400,
    height: 400,
    format: 'jpg',
    context: 'team',
    caption: 'John Doe, CEO & Founder',
    parentPageUrl: 'https://www.kdm-assoc.com/about/team',
    fileSize: 85000,
    downloaded: true,
  },
  {
    id: 'img-004',
    sourceUrl: 'https://www.kdm-assoc.com/images/services-overview.jpg',
    localPath: '/kdm-content-migration/media/images/content/services-overview.jpg',
    alt: 'Overview of KDM services',
    title: null,
    width: 800,
    height: 600,
    format: 'jpg',
    context: 'content',
    caption: null,
    parentPageUrl: 'https://www.kdm-assoc.com/',
    fileSize: 125000,
    downloaded: true,
  },
  {
    id: 'img-005',
    sourceUrl: 'https://www.kdm-assoc.com/images/certification-badge.png',
    localPath: null,
    alt: null,
    title: null,
    width: 150,
    height: 150,
    format: 'png',
    context: 'content',
    caption: null,
    parentPageUrl: 'https://www.kdm-assoc.com/services/iso-certification',
    fileSize: null,
    downloaded: false,
  },
];

export const mockVideos: VideoAsset[] = [
  {
    id: 'vid-001',
    platform: 'youtube',
    url: 'https://www.youtube.com/watch?v=abc123',
    embedCode: '<iframe src="https://www.youtube.com/embed/abc123" frameborder="0" allowfullscreen></iframe>',
    videoId: 'abc123',
    thumbnailUrl: 'https://img.youtube.com/vi/abc123/maxresdefault.jpg',
    title: 'ISO Certification Process Overview',
    description: 'Learn about the ISO certification process and how KDM Associates can help your organization achieve certification.',
    duration: '5:32',
    parentPageUrl: 'https://www.kdm-assoc.com/services/iso-certification',
    context: 'embedded',
  },
  {
    id: 'vid-002',
    platform: 'youtube',
    url: 'https://www.youtube.com/watch?v=def456',
    embedCode: '<iframe src="https://www.youtube.com/embed/def456" frameborder="0" allowfullscreen></iframe>',
    videoId: 'def456',
    thumbnailUrl: 'https://img.youtube.com/vi/def456/maxresdefault.jpg',
    title: 'CMMC 2.0 Explained',
    description: 'Understanding the new CMMC 2.0 requirements and how to prepare for certification.',
    duration: '8:15',
    parentPageUrl: 'https://www.kdm-assoc.com/services/cmmc-compliance',
    context: 'embedded',
  },
  {
    id: 'vid-003',
    platform: 'vimeo',
    url: 'https://vimeo.com/789012',
    embedCode: '<iframe src="https://player.vimeo.com/video/789012" frameborder="0" allowfullscreen></iframe>',
    videoId: '789012',
    thumbnailUrl: null,
    title: 'Client Success Story: Precision Manufacturing',
    description: 'Hear how Precision Manufacturing achieved AS9100 certification with KDM Associates.',
    duration: '3:45',
    parentPageUrl: 'https://www.kdm-assoc.com/case-studies/precision-manufacturing',
    context: 'embedded',
  },
];

export const mockDocuments: DocumentAsset[] = [
  {
    id: 'doc-001',
    url: 'https://www.kdm-assoc.com/downloads/iso-9001-guide.pdf',
    localPath: '/kdm-content-migration/media/documents/pdfs/iso-9001-guide.pdf',
    fileName: 'iso-9001-guide.pdf',
    fileType: 'pdf',
    fileSize: 2500000,
    linkText: 'Download ISO 9001 Implementation Guide',
    parentPageUrl: 'https://www.kdm-assoc.com/resources/whitepapers',
    downloaded: true,
  },
  {
    id: 'doc-002',
    url: 'https://www.kdm-assoc.com/downloads/cmmc-checklist.pdf',
    localPath: '/kdm-content-migration/media/documents/pdfs/cmmc-checklist.pdf',
    fileName: 'cmmc-checklist.pdf',
    fileType: 'pdf',
    fileSize: 850000,
    linkText: 'CMMC Readiness Checklist',
    parentPageUrl: 'https://www.kdm-assoc.com/services/cmmc-compliance',
    downloaded: true,
  },
  {
    id: 'doc-003',
    url: 'https://www.kdm-assoc.com/downloads/case-study-aerospace.pdf',
    localPath: '/kdm-content-migration/media/documents/pdfs/case-study-aerospace.pdf',
    fileName: 'case-study-aerospace.pdf',
    fileType: 'pdf',
    fileSize: 1200000,
    linkText: 'Aerospace Case Study: From Zero to AS9100',
    parentPageUrl: 'https://www.kdm-assoc.com/case-studies',
    downloaded: true,
  },
];

export const mockMigrationReport: MigrationReport = {
  siteUrl: 'https://www.kdm-assoc.com',
  crawlDate: '2026-01-18T16:30:00Z',
  summary: {
    totalPages: 47,
    pagesByType: {
      home: 1,
      about: 4,
      services: 8,
      blog: 15,
      'case-study': 6,
      resources: 5,
      contact: 1,
      legal: 3,
      other: 4,
    },
    totalImages: 156,
    totalVideos: 8,
    totalDocuments: 12,
    totalWordCount: 28500,
  },
  contentAudit: {
    highValuePages: [
      'https://www.kdm-assoc.com/',
      'https://www.kdm-assoc.com/services/iso-certification',
      'https://www.kdm-assoc.com/services/cmmc-compliance',
      'https://www.kdm-assoc.com/about',
      'https://www.kdm-assoc.com/contact',
    ],
    outdatedContent: [
      'https://www.kdm-assoc.com/blog/2022-quality-trends',
      'https://www.kdm-assoc.com/events/2023-conference',
    ],
    duplicateContent: [],
    missingMetadata: [
      'https://www.kdm-assoc.com/blog/post-15',
      'https://www.kdm-assoc.com/resources/webinar-3',
    ],
  },
  migrationPriority: {
    priority1: [
      'https://www.kdm-assoc.com/',
      'https://www.kdm-assoc.com/services',
      'https://www.kdm-assoc.com/services/iso-certification',
      'https://www.kdm-assoc.com/services/cmmc-compliance',
      'https://www.kdm-assoc.com/contact',
    ],
    priority2: [
      'https://www.kdm-assoc.com/about',
      'https://www.kdm-assoc.com/about/team',
      'https://www.kdm-assoc.com/case-studies',
    ],
    priority3: [
      'https://www.kdm-assoc.com/blog',
      'https://www.kdm-assoc.com/resources',
    ],
    archive: [
      'https://www.kdm-assoc.com/events/2023-conference',
    ],
  },
  urlMapping: [
    { oldUrl: 'https://www.kdm-assoc.com/', newUrl: '/', redirectType: '301', notes: 'Homepage' },
    { oldUrl: 'https://www.kdm-assoc.com/about', newUrl: '/about', redirectType: '301', notes: '' },
    { oldUrl: 'https://www.kdm-assoc.com/services/iso-certification', newUrl: '/services/iso-certification', redirectType: '301', notes: '' },
  ],
  mediaOptimization: {
    imagesNeedingCompression: [
      'https://www.kdm-assoc.com/images/hero-home.jpg',
      'https://www.kdm-assoc.com/images/hero-about.jpg',
    ],
    imagesNeedingAltText: [
      'https://www.kdm-assoc.com/images/certification-badge.png',
      'https://www.kdm-assoc.com/images/partner-logo-3.png',
    ],
    brokenMediaLinks: [
      'https://www.kdm-assoc.com/images/legacy-banner.jpg',
    ],
  },
  contentGaps: [
    'No dedicated ITAR compliance page',
    'Team bios are incomplete',
    'Missing client testimonials on service pages',
  ],
  recommendations: [
    'Add meta descriptions to 2 pages missing them',
    'Add alt text to 14 images',
    'Compress 8 large hero images for faster loading',
    'Update 2 outdated blog posts or archive them',
    'Create dedicated ITAR compliance service page',
    'Complete team member bios with photos',
    'Add client testimonials to service pages',
  ],
};
