import { Timestamp } from "firebase/firestore";

export const mockInstructorCohorts = [
  {
    id: "cohort-1",
    title: "CMMC Level 1 Certification - Spring 2026",
    description: "Comprehensive 12-week program covering all CMMC Level 1 requirements",
    instructorId: "instructor-1",
    startDate: Timestamp.fromDate(new Date("2026-03-15")),
    endDate: Timestamp.fromDate(new Date("2026-06-07")),
    duration: 12,
    maxParticipants: 20,
    currentEnrollment: 14,
    status: "active",
    level: "beginner",
    completedSessions: 4,
    totalSessions: 12,
    averageAttendance: 92,
    averageScore: 85,
    upcomingSession: {
      date: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
      topic: "System and Communications Protection",
      duration: 120
    },
    createdAt: Timestamp.fromDate(new Date(Date.now() - 60 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.now(),
  },
  {
    id: "cohort-2",
    title: "CMMC Level 2 Advanced Training",
    description: "Advanced 12-week cohort for organizations pursuing CMMC Level 2 certification",
    instructorId: "instructor-1",
    startDate: Timestamp.fromDate(new Date("2026-04-01")),
    endDate: Timestamp.fromDate(new Date("2026-06-24")),
    duration: 12,
    maxParticipants: 15,
    currentEnrollment: 8,
    status: "active",
    level: "advanced",
    completedSessions: 2,
    totalSessions: 12,
    averageAttendance: 88,
    averageScore: 78,
    upcomingSession: {
      date: Timestamp.fromDate(new Date(Date.now() + 5 * 24 * 60 * 60 * 1000)),
      topic: "Configuration Management",
      duration: 150
    },
    createdAt: Timestamp.fromDate(new Date(Date.now() - 45 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.now(),
  },
  {
    id: "cohort-3",
    title: "CMMC Fundamentals - Fast Track",
    description: "Accelerated 8-week program for small businesses new to CMMC compliance",
    instructorId: "instructor-1",
    startDate: Timestamp.fromDate(new Date("2026-02-15")),
    endDate: Timestamp.fromDate(new Date("2026-04-10")),
    duration: 8,
    maxParticipants: 25,
    currentEnrollment: 22,
    status: "completed",
    level: "beginner",
    completedSessions: 8,
    totalSessions: 8,
    averageAttendance: 95,
    averageScore: 88,
    createdAt: Timestamp.fromDate(new Date(Date.now() - 90 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.fromDate(new Date(Date.now() - 30 * 24 * 60 * 60 * 1000)),
  },
  {
    id: "cohort-4",
    title: "CMMC Policy Development Workshop",
    description: "Specialized 12-week cohort focused on developing compliant security policies",
    instructorId: "instructor-1",
    startDate: Timestamp.fromDate(new Date("2026-05-01")),
    endDate: Timestamp.fromDate(new Date("2026-07-24")),
    duration: 12,
    maxParticipants: 20,
    currentEnrollment: 5,
    status: "scheduled",
    level: "intermediate",
    completedSessions: 0,
    totalSessions: 12,
    createdAt: Timestamp.fromDate(new Date(Date.now() - 15 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.now(),
  }
];

export const mockInstructorStats = {
  totalCohorts: 4,
  activeCohorts: 2,
  totalStudents: 49,
  completionRate: 94,
  averageRating: 4.7,
  totalRevenue: 142500,
  upcomingSessions: 3,
  pendingReviews: 8,
};

export const mockInstructorReviews = [
  {
    id: "review-1",
    cohortId: "cohort-3",
    cohortTitle: "CMMC Fundamentals - Fast Track",
    studentName: "John Anderson",
    studentEmail: "j.anderson@techcorp.com",
    rating: 5,
    comment: "Excellent instructor! Very knowledgeable and patient. The course materials were comprehensive and easy to follow.",
    helpful: 12,
    createdAt: Timestamp.fromDate(new Date(Date.now() - 25 * 24 * 60 * 60 * 1000)),
  },
  {
    id: "review-2",
    cohortId: "cohort-1",
    cohortTitle: "CMMC Level 1 Certification - Spring 2026",
    studentName: "Sarah Martinez",
    studentEmail: "s.martinez@defensetech.com",
    rating: 5,
    comment: "Great course structure and very practical examples. The instructor made complex topics easy to understand.",
    helpful: 8,
    createdAt: Timestamp.fromDate(new Date(Date.now() - 10 * 24 * 60 * 60 * 1000)),
  },
  {
    id: "review-3",
    cohortId: "cohort-2",
    cohortTitle: "CMMC Level 2 Advanced Training",
    studentName: "Michael Chen",
    studentEmail: "m.chen@aerospace.com",
    rating: 4,
    comment: "Very thorough coverage of advanced topics. Would appreciate more hands-on exercises.",
    helpful: 5,
    createdAt: Timestamp.fromDate(new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)),
  },
  {
    id: "review-4",
    cohortId: "cohort-3",
    cohortTitle: "CMMC Fundamentals - Fast Track",
    studentName: "Emily Rodriguez",
    studentEmail: "e.rodriguez@manufacturing.com",
    rating: 5,
    comment: "Outstanding instructor! The fast-track format was perfect for our timeline. Highly recommend!",
    helpful: 15,
    createdAt: Timestamp.fromDate(new Date(Date.now() - 28 * 24 * 60 * 60 * 1000)),
  }
];

export const mockUpcomingSessions = [
  {
    id: "session-1",
    cohortId: "cohort-1",
    cohortTitle: "CMMC Level 1 Certification - Spring 2026",
    topic: "System and Communications Protection",
    date: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    startTime: "14:00",
    duration: 120,
    enrolledCount: 14,
    materialsReady: true,
  },
  {
    id: "session-2",
    cohortId: "cohort-2",
    cohortTitle: "CMMC Level 2 Advanced Training",
    topic: "Configuration Management",
    date: Timestamp.fromDate(new Date(Date.now() + 5 * 24 * 60 * 60 * 1000)),
    startTime: "13:00",
    duration: 150,
    enrolledCount: 8,
    materialsReady: true,
  },
  {
    id: "session-3",
    cohortId: "cohort-1",
    cohortTitle: "CMMC Level 1 Certification - Spring 2026",
    topic: "Incident Response Planning",
    date: Timestamp.fromDate(new Date(Date.now() + 9 * 24 * 60 * 60 * 1000)),
    startTime: "14:00",
    duration: 120,
    enrolledCount: 14,
    materialsReady: false,
  }
];
