import { Timestamp } from "firebase/firestore";

// Mock Leads
export const mockLeads = [
  {
    id: "lead-1",
    name: "John Smith",
    email: "john.smith@acmemfg.com",
    phone: "(555) 123-4567",
    company: "Acme Manufacturing",
    industry: "Aerospace",
    serviceType: "ISO 9001 Certification",
    source: "website",
    status: "new",
    partnerId: null,
    assignedAt: null,
    tenantId: "kdm",
    notes: "Interested in ISO certification for new DoD contract",
    followUpDate: Timestamp.fromDate(new Date(Date.now() + 7 * 24 * 60 * 60 * 1000)),
    lastActivityAt: Timestamp.now(),
    routingScore: 85,
    routingReason: "High match for aerospace expertise",
    capturedAt: Timestamp.fromDate(new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.now(),
  },
  {
    id: "lead-2",
    name: "Sarah Johnson",
    email: "sjohnson@precisionparts.com",
    phone: "(555) 234-5678",
    company: "Precision Parts Inc",
    industry: "Defense",
    serviceType: "CMMC Compliance",
    source: "event",
    status: "contacted",
    partnerId: "current-partner-id",
    assignedAt: Timestamp.fromDate(new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)),
    tenantId: "kdm",
    notes: "Needs CMMC Level 2 certification urgently",
    followUpDate: Timestamp.fromDate(new Date(Date.now() + 3 * 24 * 60 * 60 * 1000)),
    lastActivityAt: Timestamp.fromDate(new Date(Date.now() - 1 * 24 * 60 * 60 * 1000)),
    routingScore: 92,
    routingReason: "Perfect match for CMMC expertise",
    capturedAt: Timestamp.fromDate(new Date(Date.now() - 10 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.now(),
  },
  {
    id: "lead-3",
    name: "Michael Chen",
    email: "mchen@techsystems.com",
    phone: "(555) 345-6789",
    company: "Tech Systems LLC",
    industry: "Electronics",
    serviceType: "Lean Manufacturing",
    source: "api",
    status: "qualified",
    partnerId: "current-partner-id",
    assignedAt: Timestamp.fromDate(new Date(Date.now() - 15 * 24 * 60 * 60 * 1000)),
    tenantId: "kdm",
    notes: "Looking to improve production efficiency by 30%",
    followUpDate: Timestamp.fromDate(new Date(Date.now() + 1 * 24 * 60 * 60 * 1000)),
    lastActivityAt: Timestamp.fromDate(new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)),
    routingScore: 78,
    routingReason: "Good fit for lean manufacturing services",
    capturedAt: Timestamp.fromDate(new Date(Date.now() - 20 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.now(),
  },
];

// Mock Introductions
export const mockIntroductions = [
  {
    id: "intro-1",
    buyerId: "buyer-1",
    buyerCompany: "Lockheed Martin",
    buyerEmail: "procurement@lockheed.com",
    smeId: "sme-1",
    smeUserId: "user-sme-1",
    smeCompany: "Advanced Composites Inc",
    smeEmail: "contact@advancedcomposites.com",
    partnerId: "current-partner-id",
    projectDescription: "Need supplier for carbon fiber components for F-35 program",
    timeline: "Q2 2026",
    budgetRange: "$500K-$1M",
    preferredContactMethod: "email" as const,
    status: "accepted" as const,
    stage: "meeting_held" as const,
    smeContactInfo: { name: "Jane Doe", phone: "(555) 111-2222" },
    meetingDate: Timestamp.fromDate(new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)),
    estimatedValue: 750000,
    stageHistory: [],
    requestedAt: Timestamp.fromDate(new Date(Date.now() - 30 * 24 * 60 * 60 * 1000)),
    respondedAt: Timestamp.fromDate(new Date(Date.now() - 28 * 24 * 60 * 60 * 1000)),
    createdAt: Timestamp.fromDate(new Date(Date.now() - 30 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.now(),
  },
  {
    id: "intro-2",
    buyerId: "buyer-2",
    buyerCompany: "Boeing Defense",
    buyerEmail: "sourcing@boeing.com",
    smeId: "sme-2",
    smeUserId: "user-sme-2",
    smeCompany: "Precision Machining Co",
    smeEmail: "info@precisionmachining.com",
    partnerId: "current-partner-id",
    projectDescription: "Titanium parts for 787 program",
    timeline: "Q3 2026",
    budgetRange: "$1M-$2M",
    preferredContactMethod: "video" as const,
    status: "accepted" as const,
    stage: "rfq_sent" as const,
    smeContactInfo: { name: "Bob Smith", phone: "(555) 222-3333" },
    meetingDate: Timestamp.fromDate(new Date(Date.now() - 14 * 24 * 60 * 60 * 1000)),
    estimatedValue: 1500000,
    stageHistory: [],
    requestedAt: Timestamp.fromDate(new Date(Date.now() - 45 * 24 * 60 * 60 * 1000)),
    respondedAt: Timestamp.fromDate(new Date(Date.now() - 42 * 24 * 60 * 60 * 1000)),
    createdAt: Timestamp.fromDate(new Date(Date.now() - 45 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.now(),
  },
  {
    id: "intro-3",
    buyerId: "buyer-3",
    buyerCompany: "Raytheon Technologies",
    buyerEmail: "vendor@raytheon.com",
    smeId: "sme-3",
    smeUserId: "user-sme-3",
    smeCompany: "Electronic Systems Ltd",
    smeEmail: "sales@electronicsystems.com",
    partnerId: "current-partner-id",
    projectDescription: "Circuit boards for missile guidance systems",
    timeline: "Q1 2026",
    budgetRange: "$250K-$500K",
    preferredContactMethod: "phone" as const,
    status: "pending" as const,
    stage: "intro" as const,
    estimatedValue: 350000,
    stageHistory: [],
    requestedAt: Timestamp.fromDate(new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)),
    createdAt: Timestamp.fromDate(new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.now(),
  },
  {
    id: "intro-4",
    buyerId: "buyer-4",
    buyerCompany: "Northrop Grumman",
    buyerEmail: "procurement@northropgrumman.com",
    smeId: "sme-4",
    smeUserId: "user-sme-4",
    smeCompany: "Stealth Materials Corp",
    smeEmail: "contact@stealthmaterials.com",
    partnerId: "current-partner-id",
    projectDescription: "Radar-absorbing materials for B-21 program",
    timeline: "Q4 2026",
    budgetRange: "$2M+",
    preferredContactMethod: "email" as const,
    status: "accepted" as const,
    stage: "award" as const,
    smeContactInfo: { name: "Alice Johnson", phone: "(555) 333-4444" },
    meetingDate: Timestamp.fromDate(new Date(Date.now() - 60 * 24 * 60 * 60 * 1000)),
    estimatedValue: 2500000,
    stageHistory: [],
    requestedAt: Timestamp.fromDate(new Date(Date.now() - 90 * 24 * 60 * 60 * 1000)),
    respondedAt: Timestamp.fromDate(new Date(Date.now() - 85 * 24 * 60 * 60 * 1000)),
    createdAt: Timestamp.fromDate(new Date(Date.now() - 90 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.now(),
  },
];

// Mock Attribution Events
export const mockAttributionEvents = [
  {
    id: "attr-1",
    partnerId: "current-partner-id",
    smeId: "sme-1",
    buyerId: "buyer-1",
    eventType: "introduction_facilitated" as const,
    revenueAmount: 75000,
    attributionPercentage: 100,
    source: "Direct Outreach",
    dealId: "DEAL-2024-001",
    notes: "Successful introduction to Lockheed Martin procurement team",
    settlementStatus: "settled" as const,
    settlementId: "settlement-1",
    createdAt: Timestamp.fromDate(new Date(Date.now() - 60 * 24 * 60 * 60 * 1000)),
    createdBy: "current-partner-id",
    isImmutable: true,
  },
  {
    id: "attr-2",
    partnerId: "current-partner-id",
    smeId: "sme-2",
    buyerId: "buyer-2",
    eventType: "service_delivered" as const,
    revenueAmount: 150000,
    attributionPercentage: 50,
    source: "Event Networking",
    dealId: "DEAL-2024-002",
    notes: "Co-delivered ISO certification consulting",
    settlementStatus: "pending" as const,
    settlementId: null,
    createdAt: Timestamp.fromDate(new Date(Date.now() - 30 * 24 * 60 * 60 * 1000)),
    createdBy: "current-partner-id",
    isImmutable: true,
  },
  {
    id: "attr-3",
    partnerId: "current-partner-id",
    smeId: "sme-3",
    buyerId: null,
    eventType: "lead_generated" as const,
    revenueAmount: 25000,
    attributionPercentage: 100,
    source: "Website",
    dealId: null,
    notes: "Generated qualified lead through content marketing",
    settlementStatus: "pending" as const,
    settlementId: null,
    createdAt: Timestamp.fromDate(new Date(Date.now() - 15 * 24 * 60 * 60 * 1000)),
    createdBy: "current-partner-id",
    isImmutable: true,
  },
];

// Mock Revenue Settlements
export const mockSettlements = [
  {
    id: "settlement-1",
    partnerId: "current-partner-id",
    periodStart: Timestamp.fromDate(new Date(2024, 10, 1)), // Nov 1, 2024
    periodEnd: Timestamp.fromDate(new Date(2024, 10, 30)), // Nov 30, 2024
    grossRevenue: 75000,
    platformFeePercentage: 10,
    platformFeeAmount: 7500,
    netRevenue: 67500,
    eventCount: 3,
    eventIds: ["attr-1"],
    eventsByType: {
      introduction_facilitated: 2,
      lead_generated: 1,
    },
    status: "paid" as const,
    settlementDate: Timestamp.fromDate(new Date(2024, 11, 15)), // Dec 15, 2024
    createdAt: Timestamp.fromDate(new Date(2024, 11, 1)),
  },
  {
    id: "settlement-2",
    partnerId: "current-partner-id",
    periodStart: Timestamp.fromDate(new Date(2024, 11, 1)), // Dec 1, 2024
    periodEnd: Timestamp.fromDate(new Date(2024, 11, 31)), // Dec 31, 2024
    grossRevenue: 125000,
    platformFeePercentage: 10,
    platformFeeAmount: 12500,
    netRevenue: 112500,
    eventCount: 5,
    eventIds: ["attr-2", "attr-3"],
    eventsByType: {
      service_delivered: 3,
      introduction_facilitated: 2,
    },
    status: "calculated" as const,
    settlementDate: Timestamp.fromDate(new Date(2025, 0, 15)), // Jan 15, 2025
    createdAt: Timestamp.fromDate(new Date(2025, 0, 1)),
  },
];

// Mock SME Clients
export const mockSmeClients = [
  {
    id: "sme-1",
    companyName: "Advanced Composites Inc",
    industry: "Aerospace",
    certifications: ["AS9100", "ISO 9001", "NADCAP"],
    capabilities: ["Carbon Fiber Manufacturing", "Composite Repair", "NDT Testing"],
    subscriptionTier: "professional" as const,
    contactName: "Jane Doe",
    contactEmail: "jane@advancedcomposites.com",
    contactPhone: "(555) 111-2222",
    partnerId: "current-partner-id",
    partnerSince: Timestamp.fromDate(new Date(2023, 5, 15)),
    activeIntroductions: 2,
    totalRevenue: 750000,
    lastActivity: Timestamp.fromDate(new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)),
    createdAt: Timestamp.fromDate(new Date(2023, 5, 15)),
  },
  {
    id: "sme-2",
    companyName: "Precision Machining Co",
    industry: "Defense",
    certifications: ["ISO 9001", "ITAR Registered"],
    capabilities: ["CNC Machining", "Titanium Processing", "Quality Inspection"],
    subscriptionTier: "enterprise" as const,
    contactName: "Bob Smith",
    contactEmail: "bob@precisionmachining.com",
    contactPhone: "(555) 222-3333",
    partnerId: "current-partner-id",
    partnerSince: Timestamp.fromDate(new Date(2022, 8, 1)),
    activeIntroductions: 3,
    totalRevenue: 1500000,
    lastActivity: Timestamp.fromDate(new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)),
    createdAt: Timestamp.fromDate(new Date(2022, 8, 1)),
  },
  {
    id: "sme-3",
    companyName: "Electronic Systems Ltd",
    industry: "Electronics",
    certifications: ["ISO 9001", "IPC-A-610", "J-STD-001"],
    capabilities: ["PCB Assembly", "Wire Harness", "Box Build"],
    subscriptionTier: "basic" as const,
    contactName: "Carol White",
    contactEmail: "carol@electronicsystems.com",
    contactPhone: "(555) 444-5555",
    partnerId: "current-partner-id",
    partnerSince: Timestamp.fromDate(new Date(2024, 0, 10)),
    activeIntroductions: 1,
    totalRevenue: 350000,
    lastActivity: Timestamp.fromDate(new Date(Date.now() - 14 * 24 * 60 * 60 * 1000)),
    createdAt: Timestamp.fromDate(new Date(2024, 0, 10)),
  },
];

// Mock Service Overlaps
export const mockServiceOverlaps = [
  {
    id: "overlap-1",
    service: "ISO 9001 Certification",
    partnerId: "current-partner-id",
    otherPartners: [
      { id: "partner-2", name: "Quality Consultants LLC", clientCount: 5 },
      { id: "partner-3", name: "Compliance Experts Inc", clientCount: 3 },
    ],
    myClientCount: 8,
    totalMarketSize: 25,
    marketShare: 32,
    overlapPercentage: 32,
    recommendations: [
      "Consider specializing in aerospace ISO certifications",
      "Partner with Quality Consultants for larger projects",
    ],
    lastUpdated: Timestamp.now(),
  },
  {
    id: "overlap-2",
    service: "CMMC Compliance",
    partnerId: "current-partner-id",
    otherPartners: [
      { id: "partner-4", name: "Cyber Defense Partners", clientCount: 7 },
    ],
    myClientCount: 4,
    totalMarketSize: 15,
    marketShare: 27,
    overlapPercentage: 47,
    recommendations: [
      "High overlap with Cyber Defense Partners - coordinate on pricing",
      "Opportunity to expand in CMMC Level 3 certifications",
    ],
    lastUpdated: Timestamp.now(),
  },
  {
    id: "overlap-3",
    service: "Lean Manufacturing",
    partnerId: "current-partner-id",
    otherPartners: [],
    myClientCount: 6,
    totalMarketSize: 8,
    marketShare: 75,
    overlapPercentage: 0,
    recommendations: [
      "Market leader position - maintain quality standards",
      "Consider training other partners to scale",
    ],
    lastUpdated: Timestamp.now(),
  },
];
