import { Timestamp } from "firebase/firestore";

export const mockSMEDashboardStats = {
  activeIntroductions: 5,
  pendingResponses: 2,
  totalRevenue: 145000,
  monthlyRevenue: 28500,
  proofPackViews: 47,
  profileViews: 123,
  certifications: 4,
  completionRate: 96,
};

export const mockSMEIntroductions = [
  {
    id: "intro-sme-1",
    buyerId: "buyer-1",
    buyerCompany: "Lockheed Martin",
    buyerContact: "Sarah Johnson",
    buyerEmail: "sarah.johnson@lmco.com",
    partnerId: "partner-1",
    partnerName: "Strategic Defense Partners",
    status: "pending",
    stage: "introduction_sent",
    projectDescription: "Advanced composite materials for next-gen fighter aircraft",
    estimatedValue: 850000,
    requestedAt: Timestamp.fromDate(new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)),
    priority: "high",
    preferredContactMethod: "email",
  },
  {
    id: "intro-sme-2",
    buyerId: "buyer-2",
    buyerCompany: "Boeing Defense",
    buyerContact: "Michael Chen",
    buyerEmail: "m.chen@boeing.com",
    partnerId: "partner-2",
    partnerName: "Aerospace Alliance Group",
    status: "accepted",
    stage: "meeting_scheduled",
    projectDescription: "Precision machining for satellite components",
    estimatedValue: 425000,
    requestedAt: Timestamp.fromDate(new Date(Date.now() - 10 * 24 * 60 * 60 * 1000)),
    respondedAt: Timestamp.fromDate(new Date(Date.now() - 8 * 24 * 60 * 60 * 1000)),
    meetingDate: Timestamp.fromDate(new Date(Date.now() + 3 * 24 * 60 * 60 * 1000)),
    priority: "medium",
    preferredContactMethod: "phone",
  },
  {
    id: "intro-sme-3",
    buyerId: "buyer-3",
    buyerCompany: "Raytheon Technologies",
    buyerContact: "Jennifer Martinez",
    buyerEmail: "j.martinez@rtx.com",
    partnerId: "partner-1",
    partnerName: "Strategic Defense Partners",
    status: "accepted",
    stage: "proposal_submitted",
    projectDescription: "Radar system components manufacturing",
    estimatedValue: 1200000,
    requestedAt: Timestamp.fromDate(new Date(Date.now() - 30 * 24 * 60 * 60 * 1000)),
    respondedAt: Timestamp.fromDate(new Date(Date.now() - 28 * 24 * 60 * 60 * 1000)),
    meetingDate: Timestamp.fromDate(new Date(Date.now() - 20 * 24 * 60 * 60 * 1000)),
    proposalSubmittedAt: Timestamp.fromDate(new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)),
    priority: "high",
    preferredContactMethod: "email",
  },
  {
    id: "intro-sme-4",
    buyerId: "buyer-4",
    buyerCompany: "Northrop Grumman",
    buyerContact: "David Thompson",
    buyerEmail: "d.thompson@ngc.com",
    partnerId: "partner-3",
    partnerName: "Defense Innovation Network",
    status: "accepted",
    stage: "award",
    projectDescription: "Stealth coating application services",
    estimatedValue: 675000,
    requestedAt: Timestamp.fromDate(new Date(Date.now() - 60 * 24 * 60 * 60 * 1000)),
    respondedAt: Timestamp.fromDate(new Date(Date.now() - 58 * 24 * 60 * 60 * 1000)),
    meetingDate: Timestamp.fromDate(new Date(Date.now() - 45 * 24 * 60 * 60 * 1000)),
    proposalSubmittedAt: Timestamp.fromDate(new Date(Date.now() - 30 * 24 * 60 * 60 * 1000)),
    contractSignedAt: Timestamp.fromDate(new Date(Date.now() - 10 * 24 * 60 * 60 * 1000)),
    priority: "high",
    preferredContactMethod: "phone",
  },
  {
    id: "intro-sme-5",
    buyerId: "buyer-5",
    buyerCompany: "General Dynamics",
    buyerContact: "Amanda Rodriguez",
    buyerEmail: "a.rodriguez@gd.com",
    partnerId: "partner-2",
    partnerName: "Aerospace Alliance Group",
    status: "pending",
    stage: "introduction_sent",
    projectDescription: "Electronic warfare system components",
    estimatedValue: 320000,
    requestedAt: Timestamp.fromDate(new Date(Date.now() - 1 * 24 * 60 * 60 * 1000)),
    priority: "medium",
    preferredContactMethod: "email",
  },
];

export const mockSMERecentActivity = [
  {
    id: "activity-1",
    type: "introduction_received",
    message: "New introduction request from Lockheed Martin",
    timestamp: Timestamp.fromDate(new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)),
    buyerCompany: "Lockheed Martin",
    priority: "high",
  },
  {
    id: "activity-2",
    type: "meeting_scheduled",
    message: "Meeting scheduled with Boeing Defense",
    timestamp: Timestamp.fromDate(new Date(Date.now() - 8 * 24 * 60 * 60 * 1000)),
    buyerCompany: "Boeing Defense",
    meetingDate: Timestamp.fromDate(new Date(Date.now() + 3 * 24 * 60 * 60 * 1000)),
  },
  {
    id: "activity-3",
    type: "proposal_submitted",
    message: "Proposal submitted to Raytheon Technologies",
    timestamp: Timestamp.fromDate(new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)),
    buyerCompany: "Raytheon Technologies",
    value: 1200000,
  },
  {
    id: "activity-4",
    type: "contract_signed",
    message: "Contract signed with Northrop Grumman",
    timestamp: Timestamp.fromDate(new Date(Date.now() - 10 * 24 * 60 * 60 * 1000)),
    buyerCompany: "Northrop Grumman",
    value: 675000,
  },
  {
    id: "activity-5",
    type: "proof_pack_viewed",
    message: "Your proof pack was viewed by General Dynamics",
    timestamp: Timestamp.fromDate(new Date(Date.now() - 1 * 24 * 60 * 60 * 1000)),
    buyerCompany: "General Dynamics",
  },
  {
    id: "activity-6",
    type: "profile_updated",
    message: "Your profile was updated",
    timestamp: Timestamp.fromDate(new Date(Date.now() - 15 * 24 * 60 * 60 * 1000)),
  },
];

export const mockSMEProofPacks = [
  {
    id: "pack-1",
    title: "Aerospace Manufacturing Capabilities",
    description: "Comprehensive portfolio of aerospace manufacturing certifications and case studies",
    documentCount: 8,
    packHealth: {
      overallScore: 92,
      completeness: 95,
      freshness: 88,
      quality: 93,
    },
    views: 47,
    shares: 12,
    lastUpdated: Timestamp.fromDate(new Date(Date.now() - 15 * 24 * 60 * 60 * 1000)),
    categories: ["AS9100", "NADCAP", "ISO 9001"],
  },
  {
    id: "pack-2",
    title: "Defense Sector Credentials",
    description: "ITAR compliance and defense industry certifications",
    documentCount: 6,
    packHealth: {
      overallScore: 88,
      completeness: 90,
      freshness: 85,
      quality: 90,
    },
    views: 34,
    shares: 8,
    lastUpdated: Timestamp.fromDate(new Date(Date.now() - 30 * 24 * 60 * 60 * 1000)),
    categories: ["ITAR", "Security Clearance", "Defense"],
  },
];

export const mockSMECertifications = [
  {
    id: "cert-1",
    name: "AS9100 Rev D",
    issuer: "SAE International",
    issueDate: Timestamp.fromDate(new Date("2023-03-15")),
    expiryDate: Timestamp.fromDate(new Date("2026-03-15")),
    status: "active",
    documentUrl: "/documents/as9100-cert.pdf",
  },
  {
    id: "cert-2",
    name: "NADCAP - Heat Treating",
    issuer: "Performance Review Institute",
    issueDate: Timestamp.fromDate(new Date("2023-06-20")),
    expiryDate: Timestamp.fromDate(new Date("2025-06-20")),
    status: "active",
    documentUrl: "/documents/nadcap-cert.pdf",
  },
  {
    id: "cert-3",
    name: "ISO 9001:2015",
    issuer: "International Organization for Standardization",
    issueDate: Timestamp.fromDate(new Date("2023-01-10")),
    expiryDate: Timestamp.fromDate(new Date("2026-01-10")),
    status: "active",
    documentUrl: "/documents/iso9001-cert.pdf",
  },
  {
    id: "cert-4",
    name: "ITAR Registration",
    issuer: "U.S. Department of State",
    issueDate: Timestamp.fromDate(new Date("2024-01-01")),
    expiryDate: Timestamp.fromDate(new Date("2025-12-31")),
    status: "active",
    documentUrl: "/documents/itar-cert.pdf",
  },
];

export const mockSMEPartners = [
  {
    id: "partner-1",
    name: "Strategic Defense Partners",
    contactName: "Robert Williams",
    email: "r.williams@sdpartners.com",
    phone: "+1-555-0201",
    introductionsCount: 12,
    activeIntroductions: 2,
    totalRevenue: 2850000,
    lastContact: Timestamp.fromDate(new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)),
    relationship: "active",
  },
  {
    id: "partner-2",
    name: "Aerospace Alliance Group",
    contactName: "Lisa Anderson",
    email: "l.anderson@aerospacealliance.com",
    phone: "+1-555-0202",
    introductionsCount: 8,
    activeIntroductions: 2,
    totalRevenue: 1650000,
    lastContact: Timestamp.fromDate(new Date(Date.now() - 10 * 24 * 60 * 60 * 1000)),
    relationship: "active",
  },
  {
    id: "partner-3",
    name: "Defense Innovation Network",
    contactName: "James Patterson",
    email: "j.patterson@defenseinnovation.com",
    phone: "+1-555-0203",
    introductionsCount: 6,
    activeIntroductions: 1,
    totalRevenue: 980000,
    lastContact: Timestamp.fromDate(new Date(Date.now() - 15 * 24 * 60 * 60 * 1000)),
    relationship: "active",
  },
];

export const mockSMEPerformanceMetrics = {
  responseTime: "< 4 hours",
  acceptanceRate: 85,
  completionRate: 96,
  averageProjectValue: 625000,
  repeatBusinessRate: 72,
  customerSatisfaction: 4.8,
  onTimeDelivery: 98,
};
