import { Timestamp } from "firebase/firestore";
import { Survey, SurveyTemplate, SurveyResponse } from "@/lib/types/survey";

export const mockSurveyTemplates: SurveyTemplate[] = [
  {
    id: "template-mbda-fpc",
    name: "MBDA FPC Client Intake Form",
    description: "Comprehensive intake form for MBDA Federal Procurement Center clients",
    category: "Certification & Compliance",
    usageCount: 45,
    sections: [
      {
        id: "section-1",
        title: "Ownership Information",
        order: 1,
        questions: [
          {
            id: "q1",
            type: "dropdown",
            title: "Prefix",
            required: false,
            options: [
              { id: "opt1", label: "Mr.", value: "mr" },
              { id: "opt2", label: "Mrs.", value: "mrs" },
              { id: "opt3", label: "Ms.", value: "ms" },
              { id: "opt4", label: "Dr.", value: "dr" },
            ],
            order: 1,
          },
          {
            id: "q2",
            type: "short_text",
            title: "First Name",
            required: true,
            validation: [{ type: "required", message: "First name is required" }],
            order: 2,
          },
          {
            id: "q3",
            type: "short_text",
            title: "Last Name",
            required: true,
            validation: [{ type: "required", message: "Last name is required" }],
            order: 3,
          },
          {
            id: "q4",
            type: "file_upload",
            title: "Professional Headshot",
            required: false,
            maxFileSize: 5242880,
            acceptedFileTypes: ["image/jpeg", "image/png"],
            order: 4,
          },
        ],
      },
      {
        id: "section-2",
        title: "Professional Identity",
        order: 2,
        questions: [
          {
            id: "q5",
            type: "short_text",
            title: "Title",
            required: true,
            order: 1,
          },
          {
            id: "q6",
            type: "dropdown",
            title: "Company Owner Ethnicity",
            required: false,
            options: [
              { id: "eth1", label: "Asian American", value: "asian" },
              { id: "eth2", label: "Black or African American", value: "black" },
              { id: "eth3", label: "Hispanic or Latino", value: "hispanic" },
              { id: "eth4", label: "Native American", value: "native" },
              { id: "eth5", label: "White", value: "white" },
              { id: "eth6", label: "Other", value: "other" },
            ],
            order: 2,
          },
          {
            id: "q7",
            type: "multiple_choice",
            title: "Minority Business Certification",
            required: false,
            allowMultiple: true,
            options: [
              { id: "cert1", label: "MBE (Minority Business Enterprise)", value: "mbe" },
              { id: "cert2", label: "WBE (Women Business Enterprise)", value: "wbe" },
              { id: "cert3", label: "DBE (Disadvantaged Business Enterprise)", value: "dbe" },
              { id: "cert4", label: "VOSB (Veteran-Owned Small Business)", value: "vosb" },
            ],
            order: 3,
          },
        ],
      },
    ],
    settings: {
      allowAnonymous: false,
      allowSaveProgress: true,
      showProgressBar: true,
      oneResponsePerUser: true,
      shuffleQuestions: false,
      showQuestionNumbers: true,
      requireAllQuestions: false,
    },
    createdAt: Timestamp.fromDate(new Date(Date.now() - 90 * 24 * 60 * 60 * 1000)),
  },
  {
    id: "template-customer-satisfaction",
    name: "Customer Satisfaction Survey",
    description: "Measure customer satisfaction and gather feedback",
    category: "Quality Assurance",
    usageCount: 128,
    sections: [
      {
        id: "section-1",
        title: "Overall Experience",
        order: 1,
        questions: [
          {
            id: "q1",
            type: "rating",
            title: "How satisfied are you with our service?",
            required: true,
            minValue: 1,
            maxValue: 5,
            order: 1,
          },
          {
            id: "q2",
            type: "scale",
            title: "How likely are you to recommend us to a friend or colleague?",
            description: "0 = Not at all likely, 10 = Extremely likely",
            required: true,
            minValue: 0,
            maxValue: 10,
            order: 2,
          },
        ],
      },
    ],
    settings: {
      allowAnonymous: true,
      allowSaveProgress: false,
      showProgressBar: true,
      oneResponsePerUser: false,
      shuffleQuestions: false,
      showQuestionNumbers: false,
      requireAllQuestions: true,
    },
    createdAt: Timestamp.fromDate(new Date(Date.now() - 60 * 24 * 60 * 60 * 1000)),
  },
];

export const mockSurveys: Survey[] = [
  {
    id: "survey-1",
    title: "Q1 2026 Client Intake Survey",
    description: "Comprehensive intake survey for new MBDA FPC clients in Q1 2026",
    createdBy: "admin-001",
    createdByName: "Admin User",
    status: "active",
    templateId: "template-mbda-fpc",
    templateName: "MBDA FPC Client Intake Form",
    sections: mockSurveyTemplates[0].sections,
    settings: mockSurveyTemplates[0].settings,
    startDate: Timestamp.fromDate(new Date("2026-01-01")),
    endDate: Timestamp.fromDate(new Date("2026-03-31")),
    maxResponses: 100,
    currentResponses: 34,
    completionRate: 78,
    averageTimeToComplete: 12.5,
    shareUrl: "https://surveys.kdmassociates.com/q1-2026-intake",
    createdAt: Timestamp.fromDate(new Date(Date.now() - 15 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.now(),
    publishedAt: Timestamp.fromDate(new Date(Date.now() - 14 * 24 * 60 * 60 * 1000)),
  },
  {
    id: "survey-2",
    title: "Customer Satisfaction - December 2025",
    description: "Monthly customer satisfaction survey for December 2025",
    createdBy: "admin-001",
    createdByName: "Admin User",
    status: "closed",
    templateId: "template-customer-satisfaction",
    templateName: "Customer Satisfaction Survey",
    sections: mockSurveyTemplates[1].sections,
    settings: mockSurveyTemplates[1].settings,
    startDate: Timestamp.fromDate(new Date("2025-12-01")),
    endDate: Timestamp.fromDate(new Date("2025-12-31")),
    currentResponses: 156,
    completionRate: 92,
    averageTimeToComplete: 3.2,
    shareUrl: "https://surveys.kdmassociates.com/csat-dec-2025",
    createdAt: Timestamp.fromDate(new Date(Date.now() - 45 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.fromDate(new Date(Date.now() - 18 * 24 * 60 * 60 * 1000)),
    publishedAt: Timestamp.fromDate(new Date(Date.now() - 44 * 24 * 60 * 60 * 1000)),
  },
  {
    id: "survey-3",
    title: "Training Needs Assessment 2026",
    description: "Identify training needs for defense contractors",
    createdBy: "admin-002",
    createdByName: "Sarah Mitchell",
    status: "draft",
    sections: [
      {
        id: "section-1",
        title: "Current Skills",
        order: 1,
        questions: [
          {
            id: "q1",
            type: "multiple_choice",
            title: "What certifications does your team currently hold?",
            required: true,
            allowMultiple: true,
            options: [
              { id: "opt1", label: "CMMC Level 1", value: "cmmc1" },
              { id: "opt2", label: "CMMC Level 2", value: "cmmc2" },
              { id: "opt3", label: "ISO 9001", value: "iso9001" },
              { id: "opt4", label: "AS9100", value: "as9100" },
            ],
            order: 1,
          },
        ],
      },
    ],
    settings: {
      allowAnonymous: false,
      allowSaveProgress: true,
      showProgressBar: true,
      oneResponsePerUser: true,
      shuffleQuestions: false,
      showQuestionNumbers: true,
      requireAllQuestions: false,
    },
    currentResponses: 0,
    completionRate: 0,
    createdAt: Timestamp.fromDate(new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.now(),
  },
];

export const mockSurveyResponses: SurveyResponse[] = [
  {
    id: "response-1",
    surveyId: "survey-1",
    respondentId: "user-sme-001",
    respondentEmail: "john.doe@aerospace.com",
    isAnonymous: false,
    answers: {
      q1: "mr",
      q2: "John",
      q3: "Doe",
      q5: "CEO",
      q6: "white",
      q7: ["mbe", "vosb"],
    },
    startedAt: Timestamp.fromDate(new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)),
    completedAt: Timestamp.fromDate(new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000)),
    timeToComplete: 15,
    status: "completed",
    createdAt: Timestamp.fromDate(new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.fromDate(new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)),
  },
  {
    id: "response-2",
    surveyId: "survey-2",
    respondentEmail: "customer@example.com",
    isAnonymous: true,
    answers: {
      q1: 5,
      q2: 9,
    },
    startedAt: Timestamp.fromDate(new Date(Date.now() - 20 * 24 * 60 * 60 * 1000)),
    completedAt: Timestamp.fromDate(new Date(Date.now() - 20 * 24 * 60 * 60 * 1000 + 3 * 60 * 1000)),
    timeToComplete: 3,
    status: "completed",
    createdAt: Timestamp.fromDate(new Date(Date.now() - 20 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.fromDate(new Date(Date.now() - 20 * 24 * 60 * 60 * 1000)),
  },
];
