// Mock data for SVP Admin pages

export const mockDashboardStats = {
  totalUsers: 1234,
  activeProofPacks: 89,
  pendingQAReviews: 23,
  revenueThisMonth: 45678,
  activeCohorts: 12,
  systemHealth: 98.5,
};

export const mockRecentActivity = [
  {
    id: "1",
    type: "user_registered",
    message: "New user registered",
    timestamp: new Date(Date.now() - 2 * 60 * 1000),
    icon: "Users",
    color: "blue",
  },
  {
    id: "2",
    type: "proof_pack_submitted",
    message: "Proof pack submitted",
    timestamp: new Date(Date.now() - 15 * 60 * 1000),
    icon: "Package",
    color: "green",
  },
  {
    id: "3",
    type: "qa_review_completed",
    message: "QA review completed",
    timestamp: new Date(Date.now() - 60 * 60 * 1000),
    icon: "ClipboardCheck",
    color: "purple",
  },
];

export const mockProofPacks = [
  {
    id: "PP-001",
    title: "Q4 2025 Defense Contract",
    submitter: "Acme Defense Corp",
    submitterId: "user-001",
    status: "approved",
    qaScore: 95,
    submittedDate: "2026-01-15",
    reviewedBy: "John Doe",
    reviewerId: "reviewer-001",
  },
  {
    id: "PP-002",
    title: "Aerospace Manufacturing Proof",
    submitter: "SkyTech Industries",
    submitterId: "user-002",
    status: "pending",
    qaScore: null,
    submittedDate: "2026-01-18",
    reviewedBy: null,
    reviewerId: null,
  },
  {
    id: "PP-003",
    title: "IT Services Contract Evidence",
    submitter: "TechSolutions LLC",
    submitterId: "user-003",
    status: "in_review",
    qaScore: null,
    submittedDate: "2026-01-17",
    reviewedBy: "Jane Smith",
    reviewerId: "reviewer-002",
  },
  {
    id: "PP-004",
    title: "Construction Project Documentation",
    submitter: "BuildRight Inc",
    submitterId: "user-004",
    status: "rejected",
    qaScore: 62,
    submittedDate: "2026-01-14",
    reviewedBy: "Mike Johnson",
    reviewerId: "reviewer-003",
  },
];

export const mockQAReviewers = [
  {
    id: "reviewer-001",
    name: "John Doe",
    email: "john@example.com",
    reviewsCompleted: 45,
    avgScore: 92,
    status: "active",
  },
  {
    id: "reviewer-002",
    name: "Jane Smith",
    email: "jane@example.com",
    reviewsCompleted: 38,
    avgScore: 88,
    status: "active",
  },
  {
    id: "reviewer-003",
    name: "Mike Johnson",
    email: "mike@example.com",
    reviewsCompleted: 52,
    avgScore: 95,
    status: "offline",
  },
  {
    id: "reviewer-004",
    name: "Sarah Williams",
    email: "sarah@example.com",
    reviewsCompleted: 41,
    avgScore: 90,
    status: "active",
  },
];

export const mockRoutingRules = [
  {
    id: "1",
    name: "Defense Contractors",
    condition: "Industry = Defense",
    assignTo: "Defense Team",
    priority: 1,
    isActive: true,
  },
  {
    id: "2",
    name: "High Value Leads",
    condition: "Revenue > $1M",
    assignTo: "Senior Sales Team",
    priority: 2,
    isActive: true,
  },
  {
    id: "3",
    name: "Technology Sector",
    condition: "Industry = Technology",
    assignTo: "Tech Team",
    priority: 3,
    isActive: true,
  },
  {
    id: "4",
    name: "Small Business",
    condition: "Employees < 50",
    assignTo: "SMB Team",
    priority: 4,
    isActive: false,
  },
];

export const mockCommissionRates = [
  {
    id: "1",
    name: "Standard Partner",
    tier: "Standard",
    rate: 15,
    minRevenue: 0,
    maxRevenue: 100000,
    isActive: true,
  },
  {
    id: "2",
    name: "Premium Partner",
    tier: "Premium",
    rate: 20,
    minRevenue: 100001,
    maxRevenue: 500000,
    isActive: true,
  },
  {
    id: "3",
    name: "Elite Partner",
    tier: "Elite",
    rate: 25,
    minRevenue: 500001,
    maxRevenue: null,
    isActive: true,
  },
];

export const mockSettlements = [
  {
    id: "SET-001",
    partner: "Acme Defense Corp",
    partnerId: "partner-001",
    amount: 12500,
    period: "Q4 2025",
    status: "paid",
    paidDate: "2026-01-15",
    invoiceNumber: "INV-2026-001",
  },
  {
    id: "SET-002",
    partner: "TechSolutions LLC",
    partnerId: "partner-002",
    amount: 8750,
    period: "Q4 2025",
    status: "pending",
    paidDate: null,
    invoiceNumber: "INV-2026-002",
  },
  {
    id: "SET-003",
    partner: "BuildRight Inc",
    partnerId: "partner-003",
    amount: 15200,
    period: "Q4 2025",
    status: "processing",
    paidDate: null,
    invoiceNumber: "INV-2026-003",
  },
  {
    id: "SET-004",
    partner: "SkyTech Industries",
    partnerId: "partner-004",
    amount: 9800,
    period: "Q3 2025",
    status: "paid",
    paidDate: "2025-10-15",
    invoiceNumber: "INV-2025-045",
  },
];

export const mockCohorts = [
  {
    id: "cohort-001",
    title: "CMMC Level 1 Foundations",
    facilitator: "CMMC Expert Team",
    facilitatorId: "instructor-001",
    startDate: "2026-02-01",
    endDate: "2026-04-30",
    participants: 42,
    maxParticipants: 50,
    status: "active",
    price: 1499,
  },
  {
    id: "cohort-002",
    title: "CMMC Level 2 Advanced",
    facilitator: "CMMC Expert Team",
    facilitatorId: "instructor-001",
    startDate: "2026-03-01",
    endDate: "2026-06-30",
    participants: 28,
    maxParticipants: 40,
    status: "enrolling",
    price: 3499,
  },
  {
    id: "cohort-003",
    title: "CMMC Level 3 Expert",
    facilitator: "CMMC Expert Team",
    facilitatorId: "instructor-001",
    startDate: "2026-04-01",
    endDate: "2026-08-31",
    participants: 15,
    maxParticipants: 25,
    status: "enrolling",
    price: 5999,
  },
];
